### ISSUE TITLE
Enable SSL on postgrest.com

### ISSUE THREAD

**Issue by begriffs** [begriffs/postgrest-docs#39]
Get a cert and configure Read The Docs to use it

**Comment by phanimahesh** [comment]
Can't you set up LE?

**Comment by begriffs** [comment]
That's an option yeah. I use LE for my own domain, although it requires updating the cert with a cron job which is automated by my server. For the docs I may have to put it on my calendar to update the cert and save the changes on Read The Docs periodically.

**Comment by phanimahesh** [comment]
A cron job can be setup to do that too. If you use DNS based verification and assuming setting cert on RTD can be scripted. I'm happy to help figure this out if you are interested.

**Comment by begriffs** [comment]
Yeah I am interested. Can you provide me a checklist of what I would need to do?

**Comment by phanimahesh** [comment]
I spoke too soon, and without thinking things through. Unfortunately, reading from http://read-the-docs.readthedocs.io/en/latest/alternate_domains.html#cname-ssl, looks like this isn't possible with RTD's hosted version directly, and for good reasons.

There is no option to make RTD generate its own LE cert and use it, either. Since they say they have a shortage of developers and ops people, it is unlikely that they'll consider implementing it, since it'll add to their support load.

I'm curious though, other than "having ssl is good", do we have any specific threat model we are trying to guard against? Postgrest is not a project of sensitive nature, and not having ssl shouldn't be an issue IMO.

**Comment by ruslantalpa** [comment]
Maybe we need to protect postgrest users from the ridicule of "web devs" and stigma that goes along with putting you "business logic" in the database, everybody know this does not scale :)

**Comment by begriffs** [comment]
@phanimahesh you're right, we have no real threats -- I don't expect anyone to do a man in the middle attack to change the content of the docs.

SSL is just basic web hygiene, a nice-to-have. It leaves a bad first impression I think that postgrest.com is not secure. I'm surprised RTD doesn't support SSL for custom domains.

**Comment by begriffs** [comment]
@phanimahesh then again, look at https://docs.haskellstack.org/en/stable/README/ for example. It's read the docs but has SSL...

**Comment by ruslantalpa** [comment]
Question, would a normal certificate help or an actual separate aws instance running the site?

**Comment by begriffs** [comment]
Their service is nice because it has a control panel and git hooks so that I can activate certain branches as being public versions and when I push to them it builds and deploys. Not that we couldn't figure out a way to do it, but their setup is nice. Maybe could proxy it behind CloudFlare or something which can add SSL to sites.

**Comment by begriffs** [comment]
I think that will do it actually. I switched nameservers to cloudflare and enabled ssl. It will probably take a little while to propagate. We'll see if it automatically gets SSL.

**Comment by begriffs** [comment]
It's alive! https://postgrest.com/en/v0.4/

**Comment by ruslantalpa** [comment]
a redirect would be nice
